version: '3.8'

networks:
  cache-network:
    name: cache-network
    driver: bridge

services:
  redis-master:
    image: redis:alpine
    container_name: redis-master
    restart: always
    ports:
      - 6379:6379
    networks:
      - cache-network

  redis-slave-a:
    image: redis:alpine
    container_name: redis-slave-a
    restart: always
    ports:
      - 7000:6379
    networks:
      - cache-network
    #volumes:
    #  - ./slave-redis.conf:/etc/redis/slave-redis.conf
    command: redis-server --replicaof redis-master 6379

  redis-slave-b:
    image: redis:alpine
    container_name: redis-slave-b
    restart: always
    ports:
      - 7001:6379
    networks:
      - cache-network
    #volumes:
    #  - ./slave-redis.conf:/etc/redis/slave-redis.conf
    command: redis-server --replicaof redis-master 6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=master:redis-master,slave-a:redis-slave-a,slave-b:redis-slave-b
    ports:
      - 8091:8081
    networks:
      - cache-network

# volumes:
#   zookeeper-data:
#     driver: local
#   kafka-data:
#       driver: local
  
